# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Slicesto3D <- function(Y, S, bma, M, N, mu_init, rho_init, A_init, sig2_init, niters, nburn, nthin, mu0, rho0, A0, musig2, sigsig2, sig2mu, sig2rho, sig2A) {
    .Call('_DimProj_Slicesto3D', PACKAGE = 'DimProj', Y, S, bma, M, N, mu_init, rho_init, A_init, sig2_init, niters, nburn, nthin, mu0, rho0, A0, musig2, sigsig2, sig2mu, sig2rho, sig2A)
}

